
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POW = 41;
  public static final int WHEN = 17;
  public static final int SHOW = 22;
  public static final int STRING_LITERAL = 56;
  public static final int LBRACKET = 49;
  public static final int INCREMENT = 42;
  public static final int CHAR = 5;
  public static final int CHAR_LITERAL = 57;
  public static final int LPAREN = 45;
  public static final int INT = 2;
  public static final int DECREMENT = 43;
  public static final int MINUS = 36;
  public static final int FOR = 18;
  public static final int RPAREN = 46;
  public static final int ENDL = 51;
  public static final int NOT = 34;
  public static final int AND = 32;
  public static final int LT = 28;
  public static final int DECIDE = 11;
  public static final int COAL = 7;
  public static final int OR = 33;
  public static final int COMMA = 52;
  public static final int BOOL = 4;
  public static final int HEX_LITERAL = 58;
  public static final int GET = 23;
  public static final int NAVIDAD = 21;
  public static final int DIV = 38;
  public static final int GEQ = 31;
  public static final int PLUS = 35;
  public static final int LOOP = 15;
  public static final int EXIT = 16;
  public static final int ASSIGN = 44;
  public static final int ID = 60;
  public static final int OF = 12;
  public static final int EOF = 0;
  public static final int RETURN = 20;
  public static final int RBRACKET = 50;
  public static final int DIV_INT = 39;
  public static final int TRUE = 24;
  public static final int error = 1;
  public static final int MOD = 40;
  public static final int NEQ = 27;
  public static final int BREAK = 19;
  public static final int WORLD = 8;
  public static final int EQ = 26;
  public static final int TIMES = 37;
  public static final int ARROW = 53;
  public static final int LBRACE = 47;
  public static final int ELSE = 14;
  public static final int BINARY_LITERAL = 59;
  public static final int FLOAT = 3;
  public static final int RBRACE = 48;
  public static final int LEQ = 30;
  public static final int END = 13;
  public static final int STRING = 6;
  public static final int LOCAL = 9;
  public static final int FLOAT_LITERAL = 55;
  public static final int FALSE = 25;
  public static final int GT = 29;
  public static final int GIFT = 10;
  public static final int INT_LITERAL = 54;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "FLOAT",
  "BOOL",
  "CHAR",
  "STRING",
  "COAL",
  "WORLD",
  "LOCAL",
  "GIFT",
  "DECIDE",
  "OF",
  "END",
  "ELSE",
  "LOOP",
  "EXIT",
  "WHEN",
  "FOR",
  "BREAK",
  "RETURN",
  "NAVIDAD",
  "SHOW",
  "GET",
  "TRUE",
  "FALSE",
  "EQ",
  "NEQ",
  "LT",
  "GT",
  "LEQ",
  "GEQ",
  "AND",
  "OR",
  "NOT",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "DIV_INT",
  "MOD",
  "POW",
  "INCREMENT",
  "DECREMENT",
  "ASSIGN",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACKET",
  "RBRACKET",
  "ENDL",
  "COMMA",
  "ARROW",
  "INT_LITERAL",
  "FLOAT_LITERAL",
  "STRING_LITERAL",
  "CHAR_LITERAL",
  "HEX_LITERAL",
  "BINARY_LITERAL",
  "ID"
  };
}

